/**
 * Todo lo que dice la interfaz, en español.
 *
 * Es el catálogo de referencia: cada clave que use una pantalla tiene que
 * estar acá. La traducción al miskito no se escribe en la app: vive en
 * `diccionario/miskito/interfaz.csv`, la llenan hablantes, y `npm run
 * contenido` la vuelca en `miq.ts`. Lo que todavía no tiene traducción se
 * muestra en español.
 *
 * `{nombre}` se reemplaza al mostrar. Las listas son frases de Piko: se elige
 * una al azar.
 *
 * Regla de tono de Piko: cuando el estudiante se equivoca, **nunca** se señala
 * el error ni se usa "mal", "incorrecto" ni "no". Se reconoce el intento y se
 * muestra la respuesta. Vale igual para cualquier lengua.
 */

export const ES = {
  // ── Portada
  'portada.lema': 'Aprendé jugando, sin internet.',
  'portada.practicar': 'Practicar sola',
  'portada.unirme': 'Unirme a la clase',
  'portada.maestro': 'Soy el maestro',
  'portada.lengua_app': 'La app en',
  'portada.minijuegos': 'Minijuegos',
  'portada.musica': 'La Música de Piko',

  // ── Comunes
  'comun.volver': 'Volver',
  'comun.xp_correctas': '{xp} XP · {correctas}/{respondidas} correctas',
  'comun.xp_total': 'XP total',
  'comun.como_va_la_clase': 'Cómo va la clase',

  // ── Práctica en solitario
  'practicar.elegir_lengua': 'Elegí la lengua',
  'practicar.elegir_tema': 'Elegí un tema',
  'practicar.todo_mezclado': 'Todo mezclado',
  'practicar.sin_contenido': 'Todavía no hay ejercicios desde esta lengua.',
  'resultado.correctas': 'Correctas',
  'resultado.mejor_racha': 'Mejor racha',
  'resultado.otra_ronda': 'Otra ronda',
  'resultado.cambiar_tema': 'Cambiar de tema',

  // ── Ejercicios
  'ejercicio.tocar_para_escuchar': 'Tocá para escuchar',
  'ejercicio.que_escuchaste': '¿Qué escuchaste?',
  'ejercicio.elegir_traduccion': 'Elegí la traducción correcta',
  'ejercicio.arma_oracion': 'Armá esta oración',
  'ejercicio.toca_palabras': 'Tocá las palabras de abajo',
  'ejercicio.comprobar': 'Comprobar',
  'ejercicio.continuar': 'Continuar',
  'ejercicio.terminar': 'Terminar',

  // ── Unirse a la clase
  'unirse.sin_red': 'El aula necesita un teléfono: los navegadores no pueden abrir sockets TCP. Desde la computadora podés jugar la práctica en solitario.',
  'unirse.buscando_maestro': 'Buscando al maestro…',
  'unirse.revisando_red': 'Revisando la red del aula…',
  'unirse.no_encontre': 'No encontré la clase. ¿Está encendido el hotspot del maestro?',
  'unirse.no_pude_entrar': 'Encontré la sala pero no pude entrar. Probá de nuevo.',
  'unirse.ip_invalida': 'Esa dirección no parece válida. Tiene que ser algo como 192.168.43.1',
  'unirse.sin_respuesta': 'No hubo respuesta en esa dirección.',
  'unirse.entraste': '¡Entraste a la clase {codigo}! ¿Cuál sos vos?',
  'unirse.ya_esta_jugando': 'ya está jugando',
  'unirse.buscando': 'Buscando…',
  'unirse.buscar_otra_vez': 'Buscar otra vez',
  'unirse.escribi_direccion': 'Escribí la dirección que ve el maestro',
  'unirse.entrar': 'Entrar',

  // ── Jugar en clase
  'jugar.sin_senal': 'Sin señal — seguí jugando, se guarda todo',
  'jugar.reintento': ' · reintento en {segundos} s',
  'jugar.esta_ronda': 'Esta ronda',
  'jugar.en_la_clase': 'En la clase',
  'jugar.esperar_ronda': 'Esperar la próxima ronda',
  'jugar.se_corto': 'Se cortó la señal. Ya vuelvo a intentar.',
  'jugar.salir': 'Salir de la clase',

  // ── Panel del maestro
  'maestro.titulo': 'Mi clase',
  'maestro.conectado': '{n} conectado',
  'maestro.conectados': '{n} conectados',
  'maestro.sala_cerrada': 'Sala cerrada',
  'maestro.antes_de_abrir': 'Antes de abrir la sala',
  'maestro.aviso_1': 'Encendé el ',
  'maestro.aviso_negrita': 'punto de acceso',
  'maestro.aviso_2': ' (hotspot) desde los ajustes de tu teléfono. Los estudiantes se conectan a esa red y ahí te encuentran. No hace falta que tengas datos ni internet.',
  'maestro.codigo': 'Código de la clase',
  'maestro.si_no_encuentra': 'Si algún teléfono no encuentra la sala, que escriba {direccion}',
  'maestro.sin_lista': 'Todavía no cargaste la lista de tu clase.',
  'maestro.usar_ejemplo': 'Usar una lista de ejemplo',
  'maestro.en_la_lista': '{n} estudiantes en la lista',
  'maestro.abriendo': 'Abriendo…',
  'maestro.abrir': 'Abrir la sala',
  'maestro.terminar_ronda': 'Terminar la ronda',
  'maestro.empezar_ronda': 'Empezar una ronda',
  'maestro.cerrar': 'Cerrar la sala',

  // ── Minijuegos
  'minijuegos.titulo': 'Minijuegos',
  'minijuegos.sub': 'Jugá con las palabras que ya aprendiste en tus lecciones.',
  'minijuegos.jugar': 'Jugar',
  'minijuegos.pronto': 'Pronto va a haber más juegos.',
  'minijuegos.repetida_explica': 'Este juego ya te dio flores hoy en este nivel. Mañana vuelve a dar, o probá otro nivel u otra lengua.',
  'minijuegos.nivel': 'Nivel',
  'minijuegos.sugerido': 'Sugerido',
  'minijuegos.segun_lecciones': 'Según tus lecciones: {nivel}',
  'minijuegos.nivel_inicial': 'Inicial',
  'minijuegos.nivel_intermedio': 'Intermedio',
  'minijuegos.nivel_avanzado': 'Avanzado',
  'minijuegos.bloqueado': 'Se abre con {n} lecciones más',
  'minijuegos.bloqueado_palabras': 'Se abre con más palabras aprendidas',
  'minijuegos.sin_vocabulario': 'Todavía no hay palabras aprendidas de {lengua}. Hacé una lección y volvé a jugar.',
  'minijuegos.ir_a_practicar': 'Ir a practicar',
  'minijuegos.cambiar_lengua': 'Podés cambiar la lengua en cualquier partida con el globo.',
  'minijuegos.escuchar': 'Escuchar',
  'minijuegos.sacuanjoches': 'Sacuanjoches',

  // ── Rayuela de Piko
  'rayuela.nombre': 'Rayuela de Piko',
  'rayuela.descripcion': 'Saltá con Piko por la rayuela eligiendo la casilla correcta.',
  'rayuela.elegir_lengua': '¿En qué lengua querés saltar?',
  'rayuela.desc_inicial': 'Palabras sencillas con dibujos de apoyo.',
  'rayuela.desc_intermedio': 'Más palabras y menos dibujos, en las dos direcciones.',
  'rayuela.desc_avanzado': 'Frases cortas y audio, sin dibujos. Escuchá y elegí.',
  'rayuela.casillas': '{n} casillas',
  'rayuela.a_saltar': '¡A saltar!',
  'rayuela.pregunta_directo': '¿Qué significa en español?',
  'rayuela.pregunta_inverso': '¿Cómo se dice en {lengua}?',
  'rayuela.pregunta_escucha': 'Escuchá a Piko. ¿Qué dijo?',
  'rayuela.etiqueta': '{lengua} · {nivel} · {n} de {total}',
  'rayuela.seguir': 'Seguir saltando',
  'rayuela.al_cielo': 'Saltar al cielo',
  'rayuela.reintentar': 'Intentar de nuevo',
  'rayuela.pista_escucha': 'Tocá el parlante para escuchar otra vez.',
  'rayuela.pista_mirar': 'Mirá bien y elegí otra casilla.',
  'rayuela.cielo': 'Cielo',
  'rayuela.salir': 'Salir de la rayuela',
  'rayuela.casilla': 'Casilla {n}: {texto}',
  'rayuela.fin_cielo': '¡Llegaste al cielo!',
  'rayuela.fin_bien': '¡Bien saltado!',
  'rayuela.fin_sin_flores': '¡Terminaste la rayuela!',
  'rayuela.fin_repetida': '¡Rayuela terminada!',
  'rayuela.sin_flores_explica': 'Con {n} de {total} al primer salto ganás sacuanjoches. Repasá estas palabras y volvé a saltar.',
  'rayuela.al_primer_salto': 'Al primer salto',
  'rayuela.volver_a_saltar': 'Volver a saltar',
  'rayuela.otra_rayuela': 'Otra rayuela',

  // ── El Trompo de Piko
  'trompo.nombre': 'El Trompo de Piko',
  'trompo.descripcion': 'Lanzá el trompo y respondé rápido para que siga girando.',
  'trompo.elegir_lengua': '¿En qué idioma querés jugar?',
  'trompo.detalle_nivel': '{n} opciones · {s} s',
  'trompo.desc_inicial': 'Palabras sencillas, dibujos de apoyo y más tiempo para pensar.',
  'trompo.desc_intermedio': 'Más opciones, menos dibujos y menos tiempo.',
  'trompo.desc_avanzado': 'Frases y audio, más rápido y sin pistas.',
  'trompo.a_jugar': '¡A jugar!',
  'trompo.preparar': 'Piko ya enrolló la cuerda. Lanzá el trompo y respondé antes de que se acabe el tiempo.',
  'trompo.lanzar': '¡Lanzar el trompo!',
  'trompo.pregunta_traduccion': '¿Cómo se dice en {lengua}?',
  'trompo.pregunta_significado': '¿Qué significa?',
  'trompo.pregunta_imagen': '¿Cómo se dice en {lengua}?',
  'trompo.pregunta_audio': 'Escuchá a Piko. ¿Qué palabra dijo?',
  'trompo.pregunta_audio_frase': 'Escuchá a Piko. ¿Qué significa?',
  'trompo.etiqueta': '{lengua} · {nivel}',
  'trompo.aciertos': '{n} de {meta} respuestas',
  'trompo.puntos': '{n} pts',
  'trompo.tiempo': 'Tiempo para responder',
  'trompo.racha': '¡Racha!',
  'trompo.gran_racha': '¡Gran racha!',
  'trompo.se_acabo_tiempo': '¡Se acabó el tiempo!',
  'trompo.era': 'Era: {respuesta}',
  'trompo.salir': 'Salir del trompo',
  'trompo.fin_completo': '¡El trompo siguió girando!',
  'trompo.fin_cayo': 'El trompo se cayó. ¡Pasa en las mejores familias!',
  'trompo.fin_repetida': '¡Partida terminada!',
  'trompo.sin_flores_explica': 'Con {meta} respuestas buenas antes de que el trompo caiga ganás sacuanjoches. ¡Lanzalo otra vez!',
  'trompo.aciertos_etiqueta': 'Aciertos',
  'trompo.mejor_racha': 'Mejor racha',
  'trompo.puntos_etiqueta': 'Puntos',
  'trompo.lanzar_otra_vez': 'Lanzar otra vez',
  'trompo.otra_partida': 'Otra partida',

  // ── Bolas chinas
  'chibolas.nombre': 'Bolas chinas',
  'chibolas.descripcion': 'Apuntá y tirá tu chibola a la que tiene la respuesta correcta.',
  'chibolas.elegir_lengua': '¿En qué idioma querés jugar?',
  'chibolas.detalle_nivel': '{n} chibolas',
  'chibolas.desc_inicial': 'Dibujos y palabras sencillas, con 3 chibolas.',
  'chibolas.desc_intermedio': '4 chibolas y menos ayudas, con audio.',
  'chibolas.desc_avanzado': 'Frases y audio, sin dibujos.',
  'chibolas.a_jugar': '¡A tirar!',
  'chibolas.como': 'Agarrá tu chibola, estirala hacia atrás apuntando y soltala para tirar.',
  'chibolas.estira_mas': '¡Estirala un poco más hacia atrás y soltala!',
  'chibolas.pregunta_traduccion': '¿Cómo se dice en {lengua}?',
  'chibolas.pregunta_significado': '¿Qué significa?',
  'chibolas.pregunta_imagen': '¿Cómo se dice en {lengua}?',
  'chibolas.pregunta_audio': 'Escuchá a Piko. ¿Qué palabra dijo?',
  'chibolas.pregunta_audio_frase': 'Escuchá a Piko. ¿Qué significa?',
  'chibolas.etiqueta': '{lengua} · {nivel} · {n} de {total}',
  'chibolas.al_hoyo': '¡Al hoyito!',
  'chibolas.reboto': '¡Uy, rebotó!',
  'chibolas.pista': 'Pista: empieza con «{inicial}» y tiene {n} letras.',
  'chibolas.pista_frase': 'Pista: empieza con «{inicial}» y tiene {n} palabras.',
  'chibolas.tirar_otra_vez': 'Tirar otra vez',
  'chibolas.seguir': 'Seguir',
  'chibolas.terminar': 'Terminar',
  'chibolas.chibola': 'Chibola: {texto}',
  'chibolas.salir': 'Salir de las chibolas',
  'chibolas.fin_bien': '¡Qué buena puntería!',
  'chibolas.fin_sin_flores': '¡Terminaste la partida!',
  'chibolas.fin_repetida': '¡Partida terminada!',
  'chibolas.sin_flores_explica': 'Con {n} de {total} al primer tiro ganás sacuanjoches. ¡Afiná la puntería y volvé a jugar!',
  'chibolas.al_primer_tiro': 'Al primer tiro',
  'chibolas.jugar_otra_vez': 'Jugar otra vez',
  'chibolas.otra_partida': 'Otra partida',

  // ── Pikito Ciego (la gallinita ciega de Piko)
  'gallinita.nombre': 'Pikito Ciego',
  'gallinita.descripcion': 'El patio está a oscuras: escuchá bien y guiá a Piko hasta la respuesta.',
  'gallinita.elegir_lengua': '¿En qué idioma querés jugar?',
  'gallinita.detalle_nivel': '{n} opciones',
  'gallinita.desc_inicial': 'Palabras sueltas con dibujos y un círculo de luz grande. Escuchá las veces que quieras.',
  'gallinita.desc_intermedio': '4 escondites, palabras parecidas y menos luz.',
  'gallinita.desc_avanzado': 'Frases, muy poca luz y respuestas que sólo se escuchan. Cada audio, dos veces nomás.',
  'gallinita.a_jugar': '¡A escuchar!',
  'gallinita.pregunta_oye_dibujo': 'Escuchá. ¿Qué dijo Piko?',
  'gallinita.pregunta_oye_significado': 'Escuchá. ¿Qué significa?',
  'gallinita.pregunta_oye_palabra': 'Escuchá bien. ¿Cuál palabra es?',
  'gallinita.pregunta_dibujo_oye': 'Escuchá cada opción. ¿Cuál nombra el dibujo?',
  'gallinita.pregunta_oye_frase': 'Escuchá la frase. ¿Qué significa?',
  'gallinita.escuchar': 'Escuchar',
  'gallinita.escuchar_opcion': 'Escuchar la opción {n}',
  'gallinita.elegir_opcion': 'Elegir la opción {n}',
  'gallinita.opcion': 'Opción {n}',
  'gallinita.escuchas_quedan': 'Te quedan {n}',
  'gallinita.sin_escuchas': 'Ya no quedan escuchas',
  'gallinita.etiqueta': '{lengua} · {nivel} · {n} de {total}',
  'gallinita.racha': '¡Racha! +{n}',
  'gallinita.gran_racha': '¡Gran racha! +{n}',
  'gallinita.perfecta': '¡Partida perfecta!',
  'gallinita.encontro': '¡Piko lo encontró!',
  'gallinita.se_choco': '¡Uy! Piko se fue por otro lado.',
  'gallinita.era': 'Era: {respuesta}',
  'gallinita.seguir': 'Seguir',
  'gallinita.terminar': 'Terminar',
  'gallinita.salir': 'Salir de Pikito Ciego',
  'gallinita.como': 'Tocá un «?» para que Piko vaya a tantear. Cuando encuentres lo que escuchaste, tocá «¡Es esta!».',
  'gallinita.ir': 'Ir a tantear el escondite {n}',
  'gallinita.busca': 'Buscá en la oscuridad',
  'gallinita.es_esta': '¡Es esta!',
  'gallinita.fin_bien': '¡Qué buen oído!',
  'gallinita.fin_sin_flores': '¡Terminaste la partida!',
  'gallinita.fin_repetida': '¡Partida terminada!',
  'gallinita.sin_flores_explica': 'Con {n} de {total} respuestas buenas ganás sacuanjoches. ¡Escuchá otra vez y volvé a jugar!',
  'gallinita.aciertos': 'Aciertos',
  'gallinita.mejor_racha': 'Mejor racha',
  'gallinita.puntos': 'Puntos',
  'gallinita.jugar_otra_vez': 'Jugar otra vez',
  'gallinita.otra_partida': 'Otra partida',

  // ── La Música de Piko
  'musica.titulo': 'La Música de Piko',
  'musica.lema': 'Aprendemos un idioma nuevo sin dejar atrás nuestra propia voz.',
  'musica.completadas': 'Canciones completadas: {n} de {total}',
  'musica.vacia_titulo': 'Pronto llegan las canciones',
  'musica.vacia': 'Las canciones entran a Piko sólo cuando quien las canta da permiso y un hablante valida la letra. ¡Ya vienen!',
  'musica.comenzar': 'Comenzar',
  'musica.repetir': 'Cantar otra vez',
  'musica.completada': 'Completada',
  'musica.lengua_region': '{lengua} · {region}',
  'musica.admin_activo': 'Modo administrador (sólo en tu computadora): todas las canciones están abiertas. Tocá los puntitos de arriba de una canción para saltar a cualquier parte. No se guardan flores ni progreso.',
  'musica.fin_admin': '¡Prueba terminada!',
  'musica.admin_sin_flores': 'En modo administrador no se ganan sacuanjoches ni se guarda la canción como completada.',
  'musica.tu_nivel': 'Tu nivel según tus lecciones de inglés: {nivel}',
  'musica.para_tu_nivel': 'Para tu nivel',
  'musica.bloqueada_nivel': 'Se abre cuando tus lecciones de inglés lleguen al nivel {nivel}, o al completar una canción de nivel {anterior}',
  'musica.en_miskito': 'Palabras de esta canción en miskito',
  'musica.en_miskito_palabra': 'En miskito:',
  'musica.miskito_validado': 'Sólo las que ya están validadas en el diccionario de Piko.',
  'musica.conoce': 'Conoce nuestra canción',
  'musica.de_donde': 'De dónde viene',
  'musica.lengua': 'Lengua',
  'musica.region': 'Región o comunidad',
  'musica.representa': 'Qué representa',
  'musica.canta': 'Canta: {quien}',
  'musica.autoria': 'Autoría: {quien}',
  'musica.cultura': 'Esta canción es parte de nuestra cultura. ¡Con ella vamos a aprender inglés!',
  'musica.cultura_mundo': 'Una canción que cantan niños de todo el mundo. ¡Con ella vamos a aprender inglés!',
  'musica.progreso': 'Parte {n} de {total}',
  'musica.flores': '{n} sacuanjoches ganadas en esta canción',
  'musica.flores_hoy': 'Hoy ya ganaste las flores de esta canción. ¡Igual practicá!',
  'musica.paso_escuchar': 'Escuchá tu canción',
  'musica.paso_cantar': 'Canta con Piko',
  'musica.escuchar_ayuda': 'Escuchá tu canción y seguí la letra con la sacuanjoche. ¡Piko baila con vos!',
  'musica.cantar_ayuda': 'Ahora cantá con Piko. ¡Fijate en el inglés de cada línea!',
  'musica.empezar_leccion': '¡A aprender inglés!',
  'musica.se_repite': '↻ Se repite',
  'musica.repite_coro': 'Repite el coro',
  'musica.aproximado': 'Significado aproximado',
  'musica.frase_titulo': 'Frase {n} de {total}',
  'musica.frase_ayuda': 'Esta frase es de tu canción. ¡Vamos a decirla en inglés!',
  'musica.frase_original': 'Así se canta',
  'musica.frase_es': '¿Qué significa?',
  'musica.frase_en': '¿Cómo lo decimos en inglés?',
  'musica.escuchar_cancion': 'En la canción',
  'musica.escuchar_ingles': 'En inglés',
  'musica.a_practicar': '¡A practicar!',
  'musica.act_completar': 'Completá la frase',
  'musica.act_usa': 'Usá esta palabra',
  'musica.act_ordenar': 'Ordená la frase',
  'musica.act_escucha': '¿Qué escuchaste?',
  'musica.completar_ayuda': '¿Qué palabra falta en inglés?',
  'musica.palabra_nueva': 'Palabra nueva',
  'musica.usa_ayuda': 'Podés usar esta palabra así:',
  'musica.usa_pregunta': '¿Cuál palabra falta?',
  'musica.ya_la_vi': '¡Ya la aprendí!',
  'musica.ordenar_ayuda': 'Tocá las palabras en orden para armar la frase.',
  'musica.comprobar': 'Comprobar',
  'musica.escucha_ayuda': 'Escuchá la frase en inglés y elegí la que oíste.',
  'musica.sin_flores_explica': 'Con la mitad de las respuestas buenas la canción queda completada, y cada 3 buenas florece una sacuanjoche. ¡Probá otra vez!',
  'musica.tocar': 'Tocar',
  'musica.pausa': 'Pausa',
  'musica.escuchar_otra_vez': 'Escuchar otra vez',
  'musica.seguir': 'Seguir',
  'musica.terminar': 'Terminar la canción',
  'musica.salir': 'Salir de la canción',
  'musica.era': 'Era: {respuesta}',
  'musica.fin_bien': '¡Qué bonito cantamos!',
  'musica.fin_sin_flores': '¡Terminamos la canción!',
  'musica.fin_repetida': '¡Canción terminada!',
  'musica.aciertos': 'Aciertos',
  'musica.mejor_racha': 'Mejor racha',
  'musica.otra_cancion': 'Otra canción',
  'musica.de_nuevo': 'Cantarla de nuevo',

  // ── Nombres de las lenguas
  'lengua.eng': 'Inglés',
  'lengua.miq': 'Miskito',
  'lengua.sum': 'Mayangna',
  'lengua.rma': 'Rama',
  'lengua.cab': 'Garífuna',
  'lengua.spa': 'Español',
  'lengua.bzk': 'Kriol',

  // ── Temas de los ejercicios
  'tema.saludos': 'Saludos',
  'tema.familia': 'La familia',
  'tema.numeros': 'Números',
  'tema.cuerpo': 'El cuerpo',
  'tema.animales': 'Animales',
  'tema.comida': 'La comida',
  'tema.naturaleza': 'La naturaleza',
  'tema.casa': 'La casa',
  'tema.escuela': 'La escuela',
  'tema.colores': 'Colores',
  'tema.acciones': 'Acciones',
  'tema.escucha': 'Escuchar',
  'tema.frases': 'Frases',
  'tema.posesion': 'Mío y tuyo',

  // ── Lo que dice Piko
  'piko.acierto': ['¡Esa es!', '¡Bien ahí!', '¡Correcto!', '¡Muy bien!', '¡Le atinaste!', '¡Así se hace!'],
  'piko.racha': ['¡Vas volando!', '¡Qué racha!', '¡No te para nadie!', '¡Seguidas!'],
  /** Para cuando se equivoca. Sin "no", sin "mal", sin aspas rojas. */
  'piko.intento': ['Casi. Mirá cómo es:', 'Buen intento. Es así:', 'Ya casi. Se dice:', 'Tranquilo, mirá:', 'La próxima sale. Es:'],
  'piko.bienvenida': ['¡Hola! Soy Piko.', '¿Jugamos un rato?', '¡Qué bueno verte!'],
  'piko.fin_bien': ['¡Terminaste! Estuviste muy bien.', '¡Qué ronda! Seguí así.', '¡Excelente trabajo!'],
  'piko.fin_normal': ['¡Terminamos! Cada vez sale mejor.', 'Buen trabajo. Practicando se aprende.', '¡Listo! Lo importante es seguir.'],
  /** Al subir de nivel: Piko trepa una rama más del madroño. */
  'piko.subir_nivel': ['¡Subimos una rama!', '¡Más arriba! Desde acá se ve todo.', '¡Tu árbol nos está llevando alto!'],
  /** Cuando el madroño pasa a la etapa siguiente. */
  'piko.arbol_crece': ['¡Mirá cómo creció tu madroño!', '¡Tu árbol está creciendo!'],
  /** Rayuela: al caer en la casilla correcta. */
  'piko.rayuela_salto': ['¡Eso!', '¡Buen salto!', '¡Así se hace!', '¡Muy bien!', '¡Bien saltado!'],
  /** Rayuela: al caer en otra casilla. Sin "no" ni "mal": se vuelve a probar. */
  'piko.rayuela_casi': ['Casi. Probá otra casilla.', 'Buen intento. Elegí otra.', 'Ya casi. Probá de nuevo.'],
  /** Chibolas: cuando el tiro rebota. Divertido, nunca regaña. */
  'piko.chibola_rebota': ['¡Uy, rebotó!', '¡Esa se escapó!', '¡Casi le pego!', '¡Ay, mi chibola!'],
  /** Gallinita ciega: cuando Piko llega a otro lugar. */
  'piko.gallinita_choca': ['¡Uy! Por acá no era.', '¡Me fui por otro lado!', '¡Ay, me perdí!'],
  /** La Música de Piko: para animar a cantar. */
  'piko.cantar': ['¡Cantemos juntos!', '¡Vos podés! Repetí conmigo.', '¡Qué bonita voz!'],
  'piko.esperando': ['Esperando a la clase…', 'Ya casi empezamos.', 'El maestro está preparando la ronda.'],
} as const;
